
CREATE TABLE USER  (
   	ID DECIMAL(19,0)  NOT NULL PRIMARY KEY ,
    NAME VARCHAR(100) NOT NULL ,
    EMAIL VARCHAR(100) NOT NULL ,
    PHONE_NUMBER VARCHAR(20) NOT NULL ,
    LOCALE CHAR(2) NOT NULL,
    BIRTH_DATE DATE NOT NULL,
    CONSTRAINT VALID_LOCALE CHECK (LOCALE IN ('US', 'CA', 'BR'))
);

CREATE SEQUENCE USER_SEQ START WITH 100 MINVALUE 100 MAXVALUE 999999;

INSERT INTO USER VALUES(1,'ANTHONY KIEDIS', 'kiedis@rhcp.com', '555-555-5555', 'CA','1962-11-1')